name: format and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '21.2.0'
      - run: npm run format
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '21.2.0'
      - run: npm run lint
